### ISSUE TITLE
Terraform 0.12 Support

### ISSUE THREAD

**Issue by nebffa** [cloudposse/terraform-aws-vpc-peering-multi-account#12]
Currently the module is inoperable with Terraform 0.12 code, it would be great if it could support Terraform 0.12 :)

**Comment by anub1s187** [comment]
Any updates on this issue as I would like to use your module

**Comment by afriedrichsen-calabrio** [comment]
Still broken as of 0.12.19 version of Terraform (despite previous indication 0.12 support was already added on 12/1/19). An example error is received when using the "complete" example provided in this repo.

`Error: Missing resource instance key

  on .terraform\modules\vpc_peering_cross_account\accepter.tf line 96, in locals:
  96:   accepter_aws_route_table_ids           = "${distinct(sort(data.aws_route_tables.accepter.ids))}"

Because data.aws_route_tables.accepter has "count" set, its attributes must be
accessed on specific instances.

For example, to correlate with indices of a referring resource, use:
    data.aws_route_tables.accepter[count.index]`

There are still numerous syntax warnings indicating this has not been properly ported to 0.12.
