### ISSUE TITLE
Need to run twice for a successful plan

### ISSUE THREAD

**Issue by e-moshaya** [cloudposse/terraform-aws-vpc-peering-multi-account#8]
```
Error: Error applying plan:

2 error(s) occurred:

* module.vpc_peering_syn_scout_dev.aws_vpc_peering_connection_options.requester: 1 error(s) occurred:

* aws_vpc_peering_connection_options.requester: Error modifying VPC Peering Connection Options: OperationNotPermitted: Peering pcx-0324fc216d5832fd3 is not active. Peering options can be added only to active peerings.
	status code: 400, request id: a0a31b88-9f31-4f02-a37f-5863bf16ec36
* module.vpc_peering_syn_scout_dev.aws_vpc_peering_connection_options.accepter: 1 error(s) occurred:

* aws_vpc_peering_connection_options.accepter: Error modifying VPC Peering Connection Options: OperationNotPermitted: Peering pcx-0324fc216d5832fd3 is not active. Peering options can be added only to active peerings.
	status code: 400, request id: f4fdc3cc-9a85-4d44-827b-2faa56b5a0ae
```

It seems as though the aws_vpc_peering_connection_options resource will not work until the peering connections are active. Is there any way for the aws_vpc_peering_connection_options resources to wait for the peers to be active before running them?

**Comment by aknysh** [comment]
@e-moshaya 
there is no way in TF to wait for a peering connection to become active.
we do `terraform apply` twice
thanks

**Comment by hato221** [comment]
@aknysh would it possible to implement sleep command (easier option) or verification if peering connection is already alive with https://www.terraform.io/docs/provisioners/local-exec.html?
I would like to use this module in pipelines, but with rerunning it and failing its not nice flow then. Thanks!

**Comment by raymondbutcher** [comment]
Unless I'm missing something, it should work if you change the `aws_vpc_peering_connection_options` resources to rely on the `aws_vpc_peering_connection_accepter` resource rather than the `aws_vpc_peering_connection` resource as it is doing now.

Here is an example that works in a single apply:

https://github.com/raymondbutcher/pretf/blob/05283cfc200f2414031d8257a7c13fc80a538d5c/examples/flatten/stacks/vpc-peering/main.tf#L18-L39

**Comment by nitrocode** [comment]
Thank you for the suggestion @raymondbutcher . I know this is an old thread but I thought I'd close the loop.

The following was added in pr https://github.com/cloudposse/terraform-aws-vpc-peering-multi-account/pull/52

https://github.com/cloudposse/terraform-aws-vpc-peering-multi-account/blob/67f1be28c474144878294d626d5650224bc60443/accepter.tf#L108-L115

https://github.com/cloudposse/terraform-aws-vpc-peering-multi-account/blob/67f1be28c474144878294d626d5650224bc60443/requester.tf#L139-L143

Looks like we have the suggester change in place which makes sense since I now need to apply this module once for it to work. 🎉
